language: php

os: linux

dist: trusty

sudo: required

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

cache:
  directories:
    - $HOME/.composer/cache/files
    - tmp/pear/download/
    - vendor/

addons:
  code_climate:
    repo_token: $CODECLIMATE_REPO_TOKEN

before_script:
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install autoconf automake autotools-dev libgcrypt11-dev libgpg-error-dev libssh2-1-dev libssl-dev libtool php5-dev shtool zlib1g-dev -y -qq
  - mkdir -p build/logs
  - phpenv config-rm xdebug.ini
  - echo -e "\n\n\n\n\n\n\n\n\n"|pecl install -f -a ssh2
  - echo "extension=ssh2.so" > ssh2.ini
  - phpenv config-add ssh2.ini
  - phpenv rehash
  - travis_retry composer self-update
  - travis_retry composer update --with-dependencies --no-interaction --dev --prefer-source

script: 
  - if [ "$TRAVIS_PHP_VERSION" = "7.0" ]; then phpdbg -qrr vendor/bin/phpunit --bootstrap tests/bootstrap.php tests/ -v --coverage-clover coverage.xml --whitelist src/; fi;
  - if [ "$TRAVIS_PHP_VERSION" != "7.0" ]; then vendor/bin/phpunit --bootstrap tests/bootstrap.php tests/ -v; fi

after_success:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_PHP_VERSION" == "7.0" ]; then travis_retry vendor/bin/test-reporter --coverage-report=coverage.xml; fi
  - if [ "$TRAVIS_PHP_VERSION" = "7.0" ]; then travis_retry bash <(curl -s https://codecov.io/bash); fi;
  - if [ "$TRAVIS_PHP_VERSION" = "7.0" ]; then travis_retry php vendor/bin/coveralls -v --coverage_clover=coverage.xml; fi;
  - if [ "$TRAVIS_PHP_VERSION" = "7.0" ]; then travis_retry php vendor/bin/codacycoverage clover coverage.xml; fi;
