<?php

use Detain\IpVlanManager\Plugin;
use PHPUnit\Framework\TestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-08-18 at 02:25:12.
 */
class PluginTest extends TestCase
{
    /**
     * @var Plugin
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Plugin();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Detain\IpVlanManager\Plugin::getHooks
     * @todo   Implement testGetHooks().
     */
    public function testGetHooks()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\IpVlanManager\Plugin::getMenu
     * @todo   Implement testGetMenu().
     */
    public function testGetMenu()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Detain\IpVlanManager\Plugin::getRequirements
     * @todo   Implement testGetRequirements().
     */
    public function testGetRequirements()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
